<a href="https://colab.research.google.com/github/amna-png/ML-internship/blob/main/work/notebooks/w03_data_contract.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/amna-png/ML-internship/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Unit of analysis + time window

*Unit of Analysis (Grain): One row represents the daily organic search performance metrics (impressions, clicks, etc.) for a single unique webpage (content_hash_id) belonging to a specific client (client_hash_id) on a specific date.
Time Window: The data covers the full historical performance partitioned by month up to the snapshot release date.

In [9]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
import duckdb
from google.colab import userdata

# DuckDB connection aur HF configuration
con = duckdb.connect()

try:
    # User ke bataye mutabiq secret key ka name 'HFtoken' hai
    HF_TOKEN = userdata.get('HFtoken')
    con.execute(f"CREATE OR REPLACE SECRET hf (TYPE huggingface, TOKEN '{HF_TOKEN}')")
except Exception as e:
    print(f"An error occurred or secret not found: {e}")
    print("Please check your Google Colab Secrets (key icon) and ensure 'HFtoken' is added and enabled.")
    HF_TOKEN = None

REL = 'hf://datasets/FlyRank/internship-warehouse'

if HF_TOKEN:
    # Check the exact date ranges, grain validation, and counts using 'report_date'
    print("Checking Grain and Time Window...")
    query_1 = f"""
    SELECT
        COUNT(*) as total_rows,
        MIN(report_date) as start_date,
        MAX(report_date) as end_date,
        COUNT(DISTINCT client_hash_id) as unique_clients,
        COUNT(DISTINCT content_hash_id) as unique_pages
    FROM read_parquet('{REL}/fact_content_daily_performance_sample.parquet')
    """
    df_grain = con.sql(query_1).df()
    print(df_grain)

Checking Grain and Time Window...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   total_rows start_date   end_date  unique_clients  unique_pages
0    11694072 2026-06-01 2026-06-30              65        409205

In [6]:
!pip install -q datasets huggingface_hub pyarrow pandas

In [7]:
from huggingface_hub import login

login()

In [10]:
from datasets import load_dataset

# Specifying a configuration name (e.g., 'fact_content_daily_performance') to fix the ValueError
dataset = load_dataset(
    "FlyRank/internship-warehouse",
    "fact_content_daily_performance"
)

print(dataset)

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/18 [00:00<?, ?files/s]

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 2.62MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 4.41MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 1.45MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.29MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.22MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 7.12MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  624kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 72.0MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 19.6kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  124MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 90.3MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  134MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 21.6MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 86.2MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 89.0MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 8.93MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  149MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  146MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/78835655 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/39 [00:00<?, ?it/s]

DatasetDict({
    train: Dataset({
        features: ['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events'],
        num_rows: 78835655
    })
})

In [11]:
from huggingface_hub import list_repo_files

files = list_repo_files(
    repo_id="FlyRank/internship-warehouse",
    repo_type="dataset"
)

for file in files:
    print(file)

.gitattributes
README.md
dim_clients.parquet
dim_content.parquet
fact_content_daily_performance/month=2025-01/data_0.parquet
fact_content_daily_performance/month=2025-02/data_0.parquet
fact_content_daily_performance/month=2025-03/data_0.parquet
fact_content_daily_performance/month=2025-04/data_0.parquet
fact_content_daily_performance/month=2025-05/data_0.parquet
fact_content_daily_performance/month=2025-06/data_0.parquet
fact_content_daily_performance/month=2025-07/data_0.parquet
fact_content_daily_performance/month=2025-08/data_0.parquet
fact_content_daily_performance/month=2025-09/data_0.parquet
fact_content_daily_performance/month=2025-10/data_0.parquet
fact_content_daily_performance/month=2025-11/data_0.parquet
fact_content_daily_performance/month=2025-12/data_0.parquet
fact_content_daily_performance/month=2026-01/data_0.parquet
fact_content_daily_performance/month=2026-02/data_0.parquet
fact_content_daily_performance/month=2026-03/data_0.parquet
fact_content_daily_performance/month=2026-04/data_0.parquet
fact_content_daily_performance/month=2026-05/data_0.parquet
fact_content_daily_performance/month=2026-06/data_0.parquet
fact_content_daily_performance_sample.parquet
fact_content_query_90d.parquet

In [12]:
for file in files:
    if "content" in file.lower() or "performance" in file.lower():
        print(file)

dim_content.parquet
fact_content_daily_performance/month=2025-01/data_0.parquet
fact_content_daily_performance/month=2025-02/data_0.parquet
fact_content_daily_performance/month=2025-03/data_0.parquet
fact_content_daily_performance/month=2025-04/data_0.parquet
fact_content_daily_performance/month=2025-05/data_0.parquet
fact_content_daily_performance/month=2025-06/data_0.parquet
fact_content_daily_performance/month=2025-07/data_0.parquet
fact_content_daily_performance/month=2025-08/data_0.parquet
fact_content_daily_performance/month=2025-09/data_0.parquet
fact_content_daily_performance/month=2025-10/data_0.parquet
fact_content_daily_performance/month=2025-11/data_0.parquet
fact_content_daily_performance/month=2025-12/data_0.parquet
fact_content_daily_performance/month=2026-01/data_0.parquet
fact_content_daily_performance/month=2026-02/data_0.parquet
fact_content_daily_performance/month=2026-03/data_0.parquet
fact_content_daily_performance/month=2026-04/data_0.parquet
fact_content_daily_performance/month=2026-05/data_0.parquet
fact_content_daily_performance/month=2026-06/data_0.parquet
fact_content_daily_performance_sample.parquet
fact_content_query_90d.parquet

In [13]:
import pandas as pd
from huggingface_hub import hf_hub_download

file_path = hf_hub_download(
    repo_id="FlyRank/internship-warehouse",
    filename="fact_content_daily_performance/month=2026-03/data_0.parquet",
    repo_type="dataset"
)

df = pd.read_parquet(file_path)

print("Rows:", len(df))
print("Columns:", df.columns.tolist())

Rows: 9841378
Columns: ['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events']

In [14]:
print("Shape:", df.shape)

print("\nColumn names:")
for col in df.columns:
    print("-", col)

Shape: (9841378, 30)

Column names:
- report_date
- client_hash_id
- content_hash_id
- client_has_gsc
- client_has_ga4
- gsc_data_available
- ga4_data_available
- gsc_impressions
- gsc_clicks
- gsc_sum_position
- gsc_avg_position
- ga4_pageviews
- ga4_sessions
- ga4_users
- ga4_engaged_sessions
- ga4_total_engagement_sec
- sessions_organic
- sessions_direct
- sessions_referral
- sessions_social
- sessions_paid
- sessions_ai
- ai_chatgpt
- ai_perplexity
- ai_gemini
- ai_copilot
- ai_claude
- ai_meta
- ai_other
- scroll_events

In [15]:
df.head()

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_paid,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events
0,2026-03-01,client_73cda7b4e4f265ea,content_b7e512995f79d5a6,True,False,True,None,20,0,67,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-03-01,client_73cda7b4e4f265ea,content_05597932fe4da067,True,False,True,None,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-03-01,client_73cda7b4e4f265ea,content_7a105f548d9c6916,True,False,True,None,125,1,616,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-03-01,client_73cda7b4e4f265ea,content_905aa32a0230694e,True,False,True,None,7,0,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-03-01,client_73cda7b4e4f265ea,content_a3ea9792f793ec72,True,False,True,None,11,0,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df.dtypes

report_date                  object
client_hash_id               object
content_hash_id              object
client_has_gsc                 bool
client_has_ga4                 bool
gsc_data_available             bool
ga4_data_available           object
gsc_impressions               int64
gsc_clicks                    int64
gsc_sum_position              int64
gsc_avg_position            float64
ga4_pageviews               float64
ga4_sessions                float64
ga4_users                   float64
ga4_engaged_sessions        float64
ga4_total_engagement_sec    float64
sessions_organic            float64
sessions_direct             float64
sessions_referral           float64
sessions_social             float64
sessions_paid               float64
sessions_ai                 float64
ai_chatgpt                  float64
ai_perplexity               float64
ai_gemini                   float64
ai_copilot                  float64
ai_claude                   float64
ai_meta                     float64
ai_other                    float64
scroll_events               float64
dtype: object

In [17]:
missing = df.isna().sum()

print(missing[missing > 0])

ga4_data_available          3018741
gsc_avg_position            6230317
ga4_pageviews               3018741
ga4_sessions                3018741
ga4_users                   3018741
ga4_engaged_sessions        3018741
ga4_total_engagement_sec    3018741
sessions_organic            3018741
sessions_direct             3018741
sessions_referral           3018741
sessions_social             3018741
sessions_paid               3018741
sessions_ai                 3018741
ai_chatgpt                  3018741
ai_perplexity               3018741
ai_gemini                   3018741
ai_copilot                  3018741
ai_claude                   3018741
ai_meta                     3018741
ai_other                    3018741
scroll_events               3018741
dtype: int64

In [18]:
print("Minimum date:", df["report_date"].min())
print("Maximum date:", df["report_date"].max())

Minimum date: 2026-03-01
Maximum date: 2026-03-31

In [19]:
# Check whether one row represents one unique
# report_date + client + content combination

grain_check = df.groupby(
    ["report_date", "client_hash_id", "content_hash_id"]
).size()

print("Total rows:", len(df))
print("Unique date-client-content combinations:", grain_check.shape[0])
print("Maximum rows per combination:", grain_check.max())

if grain_check.max() == 1:
    print("✅ Grain confirmed: one row per report_date × client × content")
else:
    print("⚠️ Duplicate combinations exist")

Total rows: 9841378
Unique date-client-content combinations: 9841378
Maximum rows per combination: 1
✅ Grain confirmed: one row per report_date × client × content

In [20]:
# Verify GSC availability in March 2026

available_rows = df[df["gsc_data_available"] == True]

print("Total March rows:", len(df))
print("Rows with GSC data available:", len(available_rows))
print("Rows without GSC data:", len(df) - len(available_rows))

Total March rows: 9841378
Rows with GSC data available: 3611061
Rows without GSC data: 6230317

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

In [21]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
# Inspect candidate fields for the Search Intelligence model

candidate_columns = [
    "gsc_impressions",
    "gsc_clicks",
    "gsc_sum_position",
    "gsc_avg_position",
    "ga4_pageviews",
    "ga4_sessions",
    "ga4_users",
    "sessions_organic",
    "sessions_direct",
    "sessions_referral",
    "sessions_social",
    "sessions_paid",
    "sessions_ai"
]

for col in candidate_columns:
    if col in df.columns:
        print(f"✅ {col}")
    else:
        print(f"❌ {col} not found")

✅ gsc_impressions
✅ gsc_clicks
✅ gsc_sum_position
✅ gsc_avg_position
✅ ga4_pageviews
✅ ga4_sessions
✅ ga4_users
✅ sessions_organic
✅ sessions_direct
✅ sessions_referral
✅ sessions_social
✅ sessions_paid
✅ sessions_ai

In [22]:
# Calculate observed CTR for March 2026

df["observed_ctr"] = (
    df["gsc_clicks"] / df["gsc_impressions"]
)

# Avoid invalid values where impressions are zero
df.loc[df["gsc_impressions"] == 0, "observed_ctr"] = None

print(df["observed_ctr"].describe())

count    3.611061e+06
mean     3.080748e-03
std      3.009151e-02
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      1.000000e+00
Name: observed_ctr, dtype: float64

In [23]:
print("CTR minimum:", df["observed_ctr"].min())
print("CTR maximum:", df["observed_ctr"].max())
print("Missing CTR:", df["observed_ctr"].isna().sum())

CTR minimum: 0.0
CTR maximum: 1.0
Missing CTR: 6230317

In [24]:
# Create position bands
df["position_band"] = pd.cut(
    df["gsc_avg_position"],
    bins=[0, 3, 5, 10, 20, 50, float("inf")],
    labels=["1-3", "4-5", "6-10", "11-20", "21-50", "51+"]
)

# Calculate expected CTR for each position band
expected_ctr = df.groupby(
    "position_band",
    observed=True
)["observed_ctr"].median()

print("Expected CTR by position band:")
print(expected_ctr)

Expected CTR by position band:
position_band
1-3      0.0
4-5      0.0
6-10     0.0
11-20    0.0
21-50    0.0
51+      0.0
Name: observed_ctr, dtype: float64

In [25]:
# Map expected CTR back to each row
df["expected_ctr"] = df["position_band"].map(expected_ctr)

# CTR gap: positive = underperforming
df["ctr_gap"] = df["expected_ctr"] - df["observed_ctr"]

print(df[[
    "gsc_avg_position",
    "observed_ctr",
    "expected_ctr",
    "ctr_gap"
]].head(10))

   gsc_avg_position  observed_ctr  expected_ctr   ctr_gap
0          3.350000      0.000000           0.0  0.000000
1          0.000000      0.000000           NaN       NaN
2          4.928000      0.008000           0.0 -0.008000
3          4.000000      0.000000           0.0  0.000000
4          2.272727      0.000000           0.0  0.000000
5          7.347280      0.004184           0.0 -0.004184
6          7.832461      0.000000           0.0  0.000000
7          3.272727      0.000000           0.0  0.000000
8          5.636364      0.000000           0.0  0.000000
9          4.500000      0.000000           0.0  0.000000

In [26]:
# DELIBERATE LEAKAGE EXPERIMENT
# We intentionally use the target itself as a feature.

leakage_df = df[
    ["gsc_avg_position", "gsc_impressions", "gsc_clicks", "ctr_gap"]
].dropna().copy()

# Intentionally leaked feature
leakage_df["leaked_ctr_gap"] = leakage_df["ctr_gap"]

print("Rows used:", len(leakage_df))
print(leakage_df.head())

Rows used: 3447872
   gsc_avg_position  gsc_impressions  gsc_clicks   ctr_gap  leaked_ctr_gap
0          3.350000               20           0  0.000000        0.000000
2          4.928000              125           1 -0.008000       -0.008000
3          4.000000                7           0  0.000000        0.000000
4          2.272727               11           0  0.000000        0.000000
5          7.347280              239           1 -0.004184       -0.004184

In [28]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

X = leakage_df[[
    "gsc_avg_position",
    "gsc_impressions",
    "gsc_clicks",
    "leaked_ctr_gap"
]]

y = leakage_df["ctr_gap"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

predictions = model.predict(X_test)

leaked_score = r2_score(y_test, predictions)

print("⚠️ LEAKED R² SCORE:", leaked_score)

⚠️ LEAKED R² SCORE: 0.999999114329082

In [34]:
# Candidate features that do not directly represent the CTR-gap target

feature_candidates = [
    "gsc_avg_position",
    "gsc_sum_position",
    "ga4_pageviews",
    "ga4_sessions",
    "ga4_users"
]

for col in feature_candidates:
    print(f"✅ {col}")

✅ gsc_avg_position
✅ gsc_sum_position
✅ ga4_pageviews
✅ ga4_sessions
✅ ga4_users

In [35]:
feature_check = df[feature_candidates].isna().sum()

print("Missing values in candidate features:")
print(feature_check)

Missing values in candidate features:
gsc_avg_position    6230317
gsc_sum_position          0
ga4_pageviews       3018741
ga4_sessions        3018741
ga4_users           3018741
dtype: int64

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

In [29]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
# Query 1: Verify grain

grain_check = df.groupby(
    ["report_date", "client_hash_id", "content_hash_id"]
).size()

print("Total rows:", len(df))
print("Unique date-client-content combinations:", grain_check.shape[0])
print("Maximum rows per combination:", grain_check.max())

assert grain_check.max() == 1

print("✅ Grain verified: one row per report_date × client × content")

Total rows: 9841378
Unique date-client-content combinations: 9841378
Maximum rows per combination: 1
✅ Grain verified: one row per report_date × client × content

In [31]:
# Query 2: Verify March 2026 slice row count and date window

# Convert values to strings explicitly to avoid comparison type mismatches (e.g. date objects vs strings)
min_date_str = str(df["report_date"].min())
max_date_str = str(df["report_date"].max())

print("Row count:", len(df))
print("Minimum date:", min_date_str)
print("Maximum date:", max_date_str)

assert min_date_str == "2026-03-01"
assert max_date_str == "2026-03-31"

print("✅ March 2026 window verified")

Row count: 9841378
Minimum date: 2026-03-01
Maximum date: 2026-03-31
✅ March 2026 window verified

In [32]:
# Query 3: Verify missing values

missing_values = df.isna().sum()

print("Columns with missing values:")
print(missing_values[missing_values > 0])

Columns with missing values:
ga4_data_available          3018741
gsc_avg_position            6230317
ga4_pageviews               3018741
ga4_sessions                3018741
ga4_users                   3018741
ga4_engaged_sessions        3018741
ga4_total_engagement_sec    3018741
sessions_organic            3018741
sessions_direct             3018741
sessions_referral           3018741
sessions_social             3018741
sessions_paid               3018741
sessions_ai                 3018741
ai_chatgpt                  3018741
ai_perplexity               3018741
ai_gemini                   3018741
ai_copilot                  3018741
ai_claude                   3018741
ai_meta                     3018741
ai_other                    3018741
scroll_events               3018741
observed_ctr                6230317
position_band               6393506
expected_ctr                6393506
ctr_gap                     6393506
dtype: int64

In [33]:
# Query 4: Verify GSC availability

gsc_available = df[df["gsc_data_available"] == True]

print("Total March rows:", len(df))
print("Rows with GSC available:", len(gsc_available))
print("Rows without GSC:", len(df) - len(gsc_available))

print("✅ GSC availability verified")

Total March rows: 9841378
Rows with GSC available: 3611061
Rows without GSC: 6230317
✅ GSC availability verified

## 4. Data limits

## 4. Data limits

- **Unbalanced history:** The dataset may contain different amounts of historical data across clients and content, so comparisons between entities may not always be equally supported.

- **GSC-only early rows:** Some early rows may have GSC data available while other analytics sources are unavailable. Therefore, absence of GA4 data should not automatically be interpreted as absence of user activity.

- **Window overlaps:** Historical or rolling-window metrics may overlap across reporting dates. Therefore, these values should not be treated as independent observations when aggregating or comparing time periods.

- **Proxy target limitation:** `ctr_gap` is a proxy for search underperformance, not a human-verified label. A high CTR gap does not prove that a page actually needs an SEO/content change.

- **Availability limitation:** Rows without the required GSC data cannot provide reliable search-performance signals and may need to be excluded from analyses that depend on GSC metrics.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.